baseURL: "https://Rayhaneh-Einollahi.github.io/" 
title: Rayhaneh Einollahi
pagination:
  pagerSize: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Experience
          url: experience/
          weight: 1
        - name: Projects
          url: projects/
          weight: 2
        - name: Awards
          url: awards/
          weight: 3
        - name: Resume
          url: cv_rosa2.pdf
          weight: 4 
        - name: My Artist Side
          url: arts/
          weight: 5
        # - name: Photography
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: "I am a Computer Engineering Student at University of Tehran."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Rayhaneh Einollahi
          subtitle: "I'm a Computer Engineering student at University of Tehran.I'm currently working on 
            a compiler backend for SAYAC embedded system, focusing on intermediate representation (IR) design,
             instruction selection, and optimization passes. I'm currently learning Advanced topics in compiler construction, 
             static program analysis. I'm interested Algorithms, Graph Theory and Compiler Design. and looking to collaborate 
             on Projects that involve complex algorithm design, language processing, or applying formal methods to real-world problems."
          imageUrl: "picture2.jpg"
          imageWidth: 200
          imageHeight: 200
          imageTitle: Rayhaneh Einollahi
          buttons:
            - name: Experience
              url: experience/
            - name: Projects
              url: projects/
            - name: Awards
              url: awards/
            - name: Resume
              url: cv_rosa2.pdf
            - name: My Artist Side
              url: arts/
            # - name: Courses
            #   url: courses/
            # - name: Data
            #   url: data/
           # - name: Newsletter
           #   url: https://pmichaillat.substack.com
            # - name: Tags
            #   url: tags/
            # - name: Talks
            #   url: talks/
            # - name: Resume
            #   url: cv_rosa2.pdf
            #- name: Archive
            #  url: archive/
    socialIcons:
        # - name: CV
        #   url: cv_rosa.pdf
        - name: Email
          url: mailto:Rayhaneheinollahi@gmail.com
        - name: Location
          url: location/
    
        # - name: Google Scholar
        #   url: https://scholar.google.com/citations?user=jwrYE5sAAAAJ&hl=fr
        - name: LinkedIn
          url: https://linkedin.com/in/rayhaneh-einollahi
        - name: GitHub
          url: https://github.com/Rayhaneh-Einollahi
        # - name: ORCID
        #   url: https://orcid.org/0000-0002-9417-1075
      

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Rayhaneh Einollahi"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
